DROP SEQUENCE SEQ1;
CREATE SEQUENCE SEQ1
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999
    NOCYCLE
    NOCACHE
    ;
    
DROP SEQUENCE SEQ2;
CREATE SEQUENCE SEQ2
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999
    NOCYCLE
    NOCACHE
    ;

DROP TABLE PRODUCT;
CREATE TABLE PRODUCT(--<상품>테이블
    products_CODE VARCHAR2(20) PRIMARY KEY,
    products_NAME VARCHAR2(5) NOT NULL,
    products_PRIZE NUMBER(8),
    products_STOCK NUMBER(4)
);
DESC PRODUCT;

DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER(--<고객>테이블
    customer_ID VARCHAR2(20) PRIMARY KEY,
    customer_NAME VARCHAR2(50),
    customer_ADDRESS VARCHAR2(255),
    customer_PHONE NUMBER(11),
    customer_EMAIL VARCHAR2(20)
);
DESC CUSTOMER;


DROP TABLE BASKET;
CREATE TABLE BASKET(--<장바구니>테이블
    CNO1 NUMBER(4) PRIMARY KEY,
    customer_ID VARCHAR2(20) REFERENCES CUSTOMER(customer_ID),
    products_CODE VARCHAR2(20) REFERENCES PRODUCT(products_CODE),
    products_AMOUNT NUMBER(4) NOT NULL,
    TOTALPAY NUMBER(10) NOT NULL
);

DROP TABLE ORDERS;
CREATE TABLE ORDERS(--<주문>테이블
    Order_NUMBER NUMBER(8) PRIMARY KEY,
    customer_ID VARCHAR2(20) REFERENCES CUSTOMER(customer_ID),
    THE_DATE DATE DEFAULT SYSDATE NOT NULL, 
    NEW_ADDRESS VARCHAR2(20) NOT NULL,
    NEW_PHONE VARCHAR2(20) NOT NULL
);

DROP TABLE Details_ORDERS;
CREATE TABLE Details_ORDERS(--<상세주문>테이블
    CNO2 NUMBER(4) PRIMARY KEY,
    Order_NUMBER NUMBER(8)REFERENCES ORDERS(Order_NUMBER),
    product_CODE VARCHAR2(20) REFERENCES PRODUCT(products_CODE),
    products_AMOUNT NUMBER(4) NOT NULL,
    TOTALPAY NUMBER(10) NOT NULL
);
    
